# site settings
title: "HYUNJAE YU"
subtitle: "Data Scientist & Big Data Analyst"
email: hjyu622@gmail.com
description: "Highly skilled Data Scientist specializing in machine learning, data analysis, and process optimization with over 4 years of experience."
baseurl: "yu-portfolio" # the subpath of your site, e.g., /blog (leave empty if publishing to root)
url: "https://glorr17.github.io" # replace with your actual GitHub Pages URL
author: "HYUNJAE YU"
street_address: "#204"
city: Paju
state: Gyeonggi
zip_code:
country: "Republic of Korea"
phone: "+82(10) 2399-9412"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of Font Awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if the value is empty
# You need to restart Jekyll for changes to have an effect
socials:
  GitHub: https://github.com/glorr17 # replace with your GitHub username
  LinkedIn: https://www.linkedin.com/in/gloriayu- # replace with your LinkedIn profile
  Email: mailto:hjyu622@gmail.com

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
